### ISSUE TITLE
no context menu when opening dropbox folder through a softlink

### ISSUE THREAD

**Issue by kapouer** [Maato/thunar-dropbox#2]
say i have ~/Dropbox
and a link to it in ~/Desktop/Dropbox
If i open that last one using thunar and right click on a file,
i don't get any dropbox context menu.
If i open it from ~/Dropbox i get the context menu.

**Comment by Maato** [comment]
Fixed with commit: e61bf4d9d882b1838881e5206f1dfa7bcd392dfd.
