### ISSUE TITLE
Thunar crash when clicking on invalid encoding Item

### ISSUE THREAD

**Issue by DanielAW** [Maato/thunar-dropbox#5]
Thunar crashes when I click on an Item in the file list which got an invalid encoding. After uninstalling thunar-dropbox, the crash didn't happen again.

The last thing Thunar reports before the crash is:

```
(thunar:17107): GLib-WARNING **: Invalid UTF-8 passed to g_io_channel_write_chars().
dropbox_write() - G_IO_STATUS_ERROR
```

Im running Arch-Linux with Thunar 1.6.3 and the thunar-dropbox AUR package 0.2.0-1

**Comment by Huddayn** [comment]
Added a fix for that:
https://github.com/Maato/thunar-dropbox/pull/6

**Comment by DanielAW** [comment]
Hi Huddayn,

thanks! A quick test shows that thunar stops crashing now in my case :smile:
But the file with the invalid encoding shows now "Move to Dropbox" option in the context menu. Is this intentional?

BTW: Thunar is now on version 1.6.4 on my system

**Comment by Huddayn** [comment]
Yes, it is intentional. It skips files with invalid encoding, because `g_io_channel_write_chars` expects valid UTF-8 and otherwise it's unable to communicate with dropbox.
