### ISSUE TITLE
View on Dropbox doesn't work.

### ISSUE THREAD

**Issue by jitka** [Maato/thunar-dropbox#7]
Hello, I tried to use your plugin. I created .rpm package for suse linux and install it. When I right click in thunar I got new opinions "Move to Dropbox" or "View on Dropbox". 

"Move to Dropbox" do not have icon, but it works properly.

"View on Dropbox" said: 

Failed to open URI "file:///tmp/dbxlaGfxbk.html#6774924214e4486d2710f3b63ff33fdb0fae1d2f689f23b0986fea8c354afdb89373beebbd685f8d719606".
Error when getting information for file '/tmp/dbxlp4UhWI.html#90f5cda539a9c212125971dc8f7ba461ba139ab146e393daf4353dce156925393d923ecd35a2b76f71d480': No such file or directory.

**Comment by leghe** [comment]
Same thing for me, the context menu stopped working some time ago. Arch Linux with xfce.

**Comment by Maato** [comment]
This is not an issue in Thunar-Dropbox.
Thunar-Dropbox simply requests a list of actions that can be performed on a file from the main Dropbox program. When you click on an option it sends a message back to the main Dropbox program to perform that action. From the description given that part seems to work correctly.
